import Head from 'next/head';
import { Coin, Denom, Extension, MsgSend, StdFee, Wallet } from '@terra-money/terra.js';

const sendTransactionWithExtension = () => {
  const extension = new Extension();
  console.log('connecting!');
  extension.connect();
  extension.on((payload) => {
    console.log(payload);
  });
  extension.on('onConnect', (w: { address: string }) => {
    const toSend = new MsgSend(w.address, 'terra14qh4q9lpzt8ffr9kd8z8922rs9nej8hf6gs2qk', {
      uusd: Math.floor(10000000 * Math.random()),
    });
    extension.post({
      msgs: [toSend],
      purgeQueue: true,
      waitForConfirmation: true,
      fee: new StdFee(1, [new Coin(Denom.USD, 1)]),
    });
  });
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <button onClick={sendTransactionWithExtension}>start a transaction!</button>
      </div>
    </div>
  );
}
